// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iavdoqzfradhdlhsgsms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhdmRvcXpmcmFkaGRsaHNnc21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDc3ODUsImV4cCI6MjA1ODQyMzc4NX0.E8kz4QD0WUQYcfH-SxTmhShzTPXv-Bfkr4zZEB2GBYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);